#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9
                                                  
bspc config border_width         0
bspc config window_gap           0
bspc config top_padding 	 20

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox state=tiled desktop=●●
bspc rule -a Guake state=floating sticky=on  

~/.config/bspwm/autostart
