#!/bin/bash

## Created By Aditya Shakya

WINMENU="$(rofi -theme-str '#inputbar { enabled: false; }' -sep "|" -dmenu -i -p 'Window Options' -width 20 -hide-scrollbar -lines 4 <<< "Hide|Pin|Lock|Close")"

            case "$WINMENU" in
                Hide) whid hide;;
                Pin) bspc node -g sticky;;
                Lock) bspc node -g locked;;
                Close) bspc node -c
            esac
